"use client";

import { useState, useEffect } from "react";

// --- BACKEND CONTEXT & TYPES ---
// Maps to: SharedRideLink.UniqueToken, SharedRideLink.ExpiresAt, GPSLog (Real-time updates)
interface ShareRideModalProps {
  commuterName: string;
  onClose: () => void;
}

export default function ShareRideModal({ commuterName, onClose }: ShareRideModalProps) {
  // In real app, this token is generated by POST /api/commuter/share-ride
  // and the ExpiresAt is returned from the backend (SharedRideLink.ExpiresAt)
  const [mockToken] = useState(`trk_${Math.random().toString(36).substring(2, 8)}`);
  const shareUrl = `https://chatco.app/track/${mockToken}`;
  
  // Simulate 30-minute expiration (1800 seconds)
  // In real app, calculate remaining time: Math.floor((new Date(ExpiresAt) - Date.now()) / 1000)
  const [timeLeft, setTimeLeft] = useState(1800); 
  const [isCopied, setIsCopied] = useState(false);
  const [isExpired, setIsExpired] = useState(false);

  // Countdown Timer
  useEffect(() => {
    const timer = setInterval(() => {
      setTimeLeft((prev) => {
        if (prev <= 1) {
          clearInterval(timer);
          setIsExpired(true);
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(timer);
  }, []);

  const formatTime = (seconds: number) => {
    const m = Math.floor(seconds / 60);
    const s = seconds % 60;
    return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(shareUrl);
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
    } catch (err) {
      // Fallback for older browsers if needed
      console.error("Failed to copy: ", err);
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-end sm:items-center justify-center p-0 sm:p-4">
      {/* Backdrop */}
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} />
      
      {/* Modal Card */}
      <div className="relative bg-white sm:rounded-3xl rounded-t-3xl shadow-2xl w-full sm:max-w-md overflow-hidden animate-slide-in-from-bottom duration-300 pb-safe">
        
        {/* Header */}
        <div className="flex items-center justify-between p-5 border-b border-gray-100">
          <div className="flex items-center gap-2">
            <h2 className="text-lg font-bold text-[#071A2E]">Share Live Location</h2>
            {!isExpired && (
              <span className="flex items-center gap-1 bg-green-50 text-green-600 text-[10px] font-bold px-2 py-0.5 rounded-full border border-green-200">
                <span className="w-1.5 h-1.5 rounded-full bg-green-500 animate-pulse" />
                LIVE
              </span>
            )}
          </div>
          <button onClick={onClose} className="w-8 h-8 rounded-full bg-gray-100 hover:bg-gray-200 flex items-center justify-center transition-colors">
            <svg className="w-4 h-4 text-gray-500" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2.5}><path strokeLinecap="round" strokeLinejoin="round" d="M6 18 18 6M6 6l12 12" /></svg>
          </button>
        </div>

        <div className="p-5 space-y-5">
          
          {/* Info Text */}
          <p className="text-sm text-gray-600 leading-relaxed">
            Anyone with this link can track your live location on the map for the next 30 minutes. 
            <span className="font-semibold text-[#071A2E]"> Do not share with untrusted individuals.</span>
          </p>

          {/* URL Box */}
          <div className="bg-[#F8FAFC] rounded-xl border border-gray-200 p-1 flex items-center gap-2">
            <div className="flex-1 px-3 py-2.5 truncate">
              <p className="text-xs text-gray-500 font-medium truncate">{shareUrl}</p>
            </div>
            <button 
              onClick={handleCopy}
              disabled={isExpired}
              className={`px-4 py-2.5 rounded-lg text-xs font-semibold transition-all flex-shrink-0 ${
                isCopied 
                  ? "bg-green-100 text-green-700" 
                  : isExpired 
                    ? "bg-gray-100 text-gray-400 cursor-not-allowed" 
                    : "bg-[#1A5FB4] text-white hover:bg-[#164A8F] shadow-sm"
              }`}
            >
              {isCopied ? "Copied!" : "Copy"}
            </button>
          </div>

          {/* Countdown Timer */}
          <div className={`flex items-center justify-center gap-3 p-4 rounded-xl border transition-colors ${
            isExpired 
              ? "bg-red-50 border-red-200" 
              : timeLeft <= 300 // Turn warning color if < 5 mins left
                ? "bg-amber-50 border-amber-200" 
                : "bg-[#F0F7FF] border-[#DAEEFF]"
          }`}>
            <svg className={`w-5 h-5 ${isExpired ? "text-red-500" : timeLeft <= 300 ? "text-amber-500" : "text-[#1A5FB4]"}`} fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
            </svg>
            <div className="text-center">
              <p className={`text-2xl font-extrabold tracking-wider ${isExpired ? "text-red-600" : timeLeft <= 300 ? "text-amber-600" : "text-[#1A5FB4]"}`}>
                {isExpired ? "00:00" : formatTime(timeLeft)}
              </p>
              <p className="text-[10px] font-medium text-gray-500 uppercase tracking-wider mt-0.5">
                {isExpired ? "Link Expired" : "Time Remaining"}
              </p>
            </div>
          </div>

          {/* Disclaimer */}
          <div className="flex gap-2 bg-gray-50 p-3 rounded-lg">
            <svg className="w-4 h-4 text-gray-400 flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="m11.25 11.25.041-.02a.75.75 0 0 1 1.063.852l-.708 2.836a.75.75 0 0 0 1.063.853l.041-.021M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Zm-9-3.75h.008v.008H12V8.25Z" />
            </svg>
            <p className="text-[11px] text-gray-500 leading-relaxed">
              Link automatically stops sharing after 30 minutes. Tracking relies on your device&apos;s GPS.
            </p>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-3 pt-1">
            <button 
              onClick={onClose}
              className="flex-1 px-4 py-3 rounded-xl text-sm font-semibold border border-gray-200 text-gray-700 hover:bg-gray-50 transition-colors"
            >
              Done
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}