<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        if (Schema::hasTable('hails')) {
            return;
        }

        Schema::create('hails', function (Blueprint $table) {
            // UUID primary key (auto-generated by the model)
            $table->uuid('id')->primary();

            // Foreign keys
            $table->uuid('commuter_id');
            $table->uuid('vehicle_id');
            $table->uuid('conductor_id')->nullable();

            // Hail location & distance
            $table->decimal('commuter_lat', 10, 7);
            $table->decimal('commuter_lng', 10, 7);
            $table->decimal('distance_m', 10, 2)->comment('Haversine distance at creation time, in meters');

            // Server-enforced lifecycle
            $table->enum('status', ['pending', 'accepted', 'rejected', 'cancelled', 'expired'])
                ->default('pending');
            $table->timestamp('expires_at');

            $table->timestamps();

            // Foreign key constraints
            $table->foreign('commuter_id')
                ->references('id')
                ->on('users')
                ->cascadeOnDelete();

            $table->foreign('vehicle_id')
                ->references('id')
                ->on('vehicles')
                ->cascadeOnDelete();

            $table->foreign('conductor_id')
                ->references('id')
                ->on('users')
                ->nullOnDelete();

            // Composite indexes for common query patterns
            $table->index(['vehicle_id', 'status']);
            $table->index(['commuter_id', 'status']);
            $table->index(['status', 'expires_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('hails');
    }
};
