// app/components/conductor/remittance/OfficialReportModal.tsx
import { RemittanceRecord } from "@/lib/remittance-history";
import { formatTime } from "@/lib/conductor-shift";
import { fmt, fmtDate, fmtDateTime } from "@/app/(conductor)/conductor-dashboard/end-of-day/helpers";

interface OfficialReportModalProps { show: boolean; onClose: () => void; activeReport: RemittanceRecord; route: string; }

export default function OfficialReportModal({ show, onClose, activeReport, route }: OfficialReportModalProps) {
  if (!show) return null;
  return (
    <div className="fixed inset-0 z-[100] flex items-end sm:items-center justify-center">
      <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={onClose} />
      <div className="relative w-full max-w-md bg-[#0F2135] border border-white/[0.08] rounded-t-3xl sm:rounded-3xl overflow-hidden shadow-2xl animate-slide-up max-h-[90vh] flex flex-col">
        <div className="flex-shrink-0 px-6 pt-6 pb-4 border-b border-white/[0.06]"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><div className="w-7 h-7 rounded-lg bg-[#1A5FB4] flex items-center justify-center"><svg className="w-4 h-4 text-white" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M19.5 14.25v-2.625a3.375 3.375 0 0 0-3.375-3.375h-1.5A1.125 1.125 0 0 1 13.5 7.125v-1.5a3.375 3.375 0 0 0-3.375-3.375H8.25m2.25 0H5.625c-.621 0-1.125.504-1.125 1.125v17.25c0 .621.504 1.125 1.125 1.125h12.75c.621 0 1.125-.504 1.125-1.125V11.25a9 9 0 0 0-9-9Z" /></svg></div><h2 className="text-white font-bold text-sm">Official Report</h2></div><button onClick={onClose} className="w-8 h-8 rounded-lg bg-white/5 flex items-center justify-center text-white/40 hover:bg-white/10 hover:text-white transition-all"><svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M6 18 18 6M6 6l12 12" /></svg></button></div></div>
        <div className="flex-1 overflow-y-auto p-6 space-y-5">
          <div className="text-center space-y-1"><h3 className="text-white font-extrabold text-xl tracking-wide">CHATCO</h3><p className="text-[10px] text-white/30 uppercase tracking-[0.2em] font-semibold">End of Day Remittance Report</p></div><div className="h-px bg-white/10" />
          <div className="grid grid-cols-2 gap-x-4 gap-y-3">
            <div><p className="text-[9px] font-bold text-white/25 uppercase tracking-wider">Date</p><p className="text-xs font-semibold text-white/80 mt-0.5">{fmtDate(activeReport.date)}</p></div><div><p className="text-[9px] font-bold text-white/25 uppercase tracking-wider">Shift ID</p><p className="text-xs font-semibold text-white/80 mt-0.5 font-mono">{activeReport.shiftId}</p></div><div><p className="text-[9px] font-bold text-white/25 uppercase tracking-wider">Conductor</p><p className="text-xs font-semibold text-white/80 mt-0.5">{activeReport.conductorName}</p></div><div><p className="text-[9px] font-bold text-white/25 uppercase tracking-wider">Driver</p><p className="text-xs font-semibold text-white/80 mt-0.5">{activeReport.driverName}</p></div><div><p className="text-[9px] font-bold text-white/25 uppercase tracking-wider">Time In</p><p className="text-xs font-semibold text-emerald-400/80 mt-0.5">{formatTime(activeReport.timeIn)}</p></div><div><p className="text-[9px] font-bold text-white/25 uppercase tracking-wider">Time Out</p><p className="text-xs font-semibold text-red-400/80 mt-0.5">{formatTime(activeReport.timeOut)}</p></div><div><p className="text-[9px] font-bold text-white/25 uppercase tracking-wider">Unit Number</p><p className="text-xs font-semibold text-white/80 mt-0.5">{activeReport.unitNumber}</p></div><div><p className="text-[9px] font-bold text-white/25 uppercase tracking-wider">Route</p><p className="text-xs font-semibold text-white/80 mt-0.5">{route}</p></div>
          </div>
          <div className="space-y-2"><p className="text-[10px] font-bold text-white/40 uppercase tracking-wider">Cashless Collection</p><div className="bg-white/[0.03] border border-white/[0.05] rounded-xl overflow-hidden"><table className="w-full"><thead><tr className="border-b border-white/[0.06]"><th className="text-left text-[9px] font-bold text-white/30 uppercase tracking-wider px-3.5 py-2.5">Method</th><th className="text-right text-[9px] font-bold text-white/30 uppercase tracking-wider px-3.5 py-2.5">Amount</th></tr></thead><tbody className="divide-y divide-white/[0.03]"><tr><td className="px-3.5 py-2.5 flex items-center gap-2"><div className="w-1.5 h-1.5 rounded-full bg-[#62A0EA]" /><span className="text-xs text-white/60">QR Scanned</span></td><td className="px-3.5 py-2.5 text-right text-xs font-bold text-[#62A0EA] tabular-nums">{fmt(activeReport.cashlessBreakdown.scanned)}</td></tr><tr><td className="px-3.5 py-2.5 flex items-center gap-2"><div className="w-1.5 h-1.5 rounded-full bg-emerald-400" /><span className="text-xs text-white/60">Prepaid</span></td><td className="px-3.5 py-2.5 text-right text-xs font-bold text-emerald-400 tabular-nums">{fmt(activeReport.cashlessBreakdown.prepaid)}</td></tr><tr><td className="px-3.5 py-2.5 flex items-center gap-2"><div className="w-1.5 h-1.5 rounded-full bg-amber-400" /><span className="text-xs text-white/60">Voucher</span></td><td className="px-3.5 py-2.5 text-right text-xs font-bold text-amber-400 tabular-nums">{fmt(activeReport.cashlessBreakdown.voucher)}</td></tr></tbody><tfoot><tr className="bg-white/[0.03]"><td className="px-3.5 py-2.5 text-[10px] font-bold text-white/50 uppercase tracking-wider">Subtotal</td><td className="px-3.5 py-2.5 text-right text-sm font-extrabold text-white tabular-nums">{fmt(activeReport.totalCashless)}</td></tr></tfoot></table></div></div>
          <div className="h-px bg-white/[0.06]" />
          <div className="space-y-3"><div className="flex items-center justify-between"><span className="text-xs text-white/50">Cash Collected</span><span className="text-sm font-bold text-amber-400 tabular-nums">{fmt(activeReport.cashDeclared)}</span></div><div className="h-px bg-white/10" /><div className="flex items-center justify-between"><div><span className="text-xs font-bold text-white/70 uppercase tracking-wider">Grand Total</span></div><span className="text-2xl font-extrabold text-[#62A0EA] tabular-nums">{fmt(activeReport.totalCashless + activeReport.cashDeclared)}</span></div></div>
          <div className="h-px bg-white/[0.06]" />
          <div className="flex items-center justify-between bg-white/[0.03] border border-white/[0.05] rounded-xl px-4 py-3"><div><p className="text-[9px] font-bold text-white/25 uppercase tracking-wider">Remittance Status</p><p className="text-xs font-semibold text-white/60 mt-0.5">Remitted to Admin</p></div><span className={`text-[9px] font-bold uppercase tracking-wider px-2.5 py-1 rounded-full ${activeReport.remittanceStatus === "Remitted" ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20" : "bg-amber-500/10 text-amber-400 border border-amber-500/20"}`}>{activeReport.remittanceStatus}</span></div>
          <p className="text-[10px] text-white/15 text-center font-mono">Generated: {fmtDateTime()}</p>
        </div>
        <div className="flex-shrink-0 px-6 py-4 border-t border-white/[0.06] flex gap-3 bg-[#0F2135]"><button onClick={onClose} className="flex-1 py-3 rounded-xl bg-white/5 border border-white/10 text-white/50 text-xs font-semibold hover:bg-white/10 transition-all">Close</button><button onClick={() => { window.print(); }} className="flex-1 py-3 rounded-xl bg-[#1A5FB4] text-white text-xs font-bold shadow-lg shadow-[#1A5FB4]/20 hover:bg-[#165a9f] transition-all flex items-center justify-center gap-1.5"><svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}><path strokeLinecap="round" strokeLinejoin="round" d="M6 12 3.269 3.125A59.769 59.769 0 0 1 21.485 12 59.768 59.768 0 0 1 3.27 20.875L5.999 12Zm0 0h7.5" /></svg>Share</button></div>
      </div>
    </div>
  );
}